# Generated by Django 3.0.8 on 2020-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0725', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='app0725/defaultimage/aaa.jpg', upload_to='images/'),
        ),
    ]
